[package]
name = "identity"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["postgres", "macros", "runtime-tokio"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.6"
