FROM rust:1.97-alpine3.23 AS build
WORKDIR /app

RUN apk add protoc

COPY . .

ARG SQLX_OFFLINE=true
RUN cargo build

FROM alpine:3.23

RUN apk add ca-certificates

COPY --from=build /app/target/debug/identity .
COPY migrations migrations
COPY config config

EXPOSE 8080

CMD ["./identity"]
