syntax = "proto3";

package identity;

option go_package = "graphophone.identity/internal/services/common/user";

service Identity {
    rpc GetProfiles(UserIds) returns (Profiles) {}
    rpc GetBasicProfile(UserId) returns (Profile) {}
    rpc GetFullProfile(FullProfileReq) returns (FullProfile) {}
    rpc CreateUser(CreateUserReq) returns (UserId) {}
    rpc DeleteUser(UserId) returns (Empty) {}
    rpc UpdateProfile(UpdateProfileReq) returns (Empty) {}
    rpc UpdateAvatar(UpdateAvatarReq) returns (Empty) {}
    rpc UpdateBanner(UpdateBannerReq) returns (Empty) {}
    rpc UpdatePassword(UpdatePasswordReq) returns (Empty) {}
    rpc VerifyPassword(VerifyPasswordReq) returns (UserId) {}
}

message Empty {}

message UserIds {
    repeated int64 user_ids = 1;
}

message Profile {
    int64 user_id = 1;
    string username = 2;
    optional string avatar_key = 3;
    optional string banner_key = 4;
}

message Profiles {
    repeated Profile profiles = 1;
}

message UserId {
    int64 user_id = 1;
}

message FullProfileReq {
    int64 user_id = 1;
    bool with_email = 2;
}

message FullProfile {
    int64 user_id = 1;
    string username = 2;
    optional string avatar_key = 3;
    optional string banner_key = 4;
    optional string first_name = 5;
    optional string last_name = 6;
    optional string bio = 7;
    optional string country = 8;
    optional string city = 9;
    optional string email = 10;
}

message CreateUserReq {
    string username = 1;
    string email = 2;
    string password = 3;
    optional string first_name = 4;
    optional string last_name = 5;
}

message UpdateProfileReq {
    int64 user_id = 1;
    string username = 2;
    string email = 3;
    optional string first_name = 4;
    optional string last_name = 5;
    optional string bio = 6;
    optional string country = 7;
    optional string city = 8;
}

message UpdateAvatarReq {
    int64 user_id = 1;
    optional bytes avatar = 2;
}

message UpdateBannerReq {
    int64 user_id = 1;
    optional bytes banner = 2;
}

message UpdatePasswordReq {
    int64 user_id = 1;
    string old_password = 2;
    string new_password = 3;
}

message VerifyPasswordReq {
    string username = 1;
    string password = 2;
}
